name: Quality

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      #      - name: Validate composer.json and composer.lock
      #        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install suggested dependencies
        run: composer install knplabs/knp-menu-bundle knplabs/knp-paginator-bundle symfony/form:^4.4

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run Coding Style Control
        run: make cs_dry_run

#      - name: Run Tests
#        run: make test
